// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: notifications/notification.proto

package prnotifications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *NProfile) Reset() {
	*x = NProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notifications_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NProfile) ProtoMessage() {}

func (x *NProfile) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NProfile.ProtoReflect.Descriptor instead.
func (*NProfile) Descriptor() ([]byte, []int) {
	return file_notifications_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username                      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ReferredUsername              string `protobuf:"bytes,2,opt,name=referredUsername,proto3" json:"referredUsername,omitempty"`
	ReferredUserProfilePictureURL string `protobuf:"bytes,3,opt,name=referredUserProfilePictureURL,proto3" json:"referredUserProfilePictureURL,omitempty"`
	Type                          string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Seen                          bool   `protobuf:"varint,5,opt,name=seen,proto3" json:"seen,omitempty"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notifications_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notifications_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Notification) GetReferredUsername() string {
	if x != nil {
		return x.ReferredUsername
	}
	return ""
}

func (x *Notification) GetReferredUserProfilePictureURL() string {
	if x != nil {
		return x.ReferredUserProfilePictureURL
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetSeen() bool {
	if x != nil {
		return x.Seen
	}
	return false
}

type NRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReferredId uint64 `protobuf:"varint,2,opt,name=referredId,proto3" json:"referredId,omitempty"`
}

func (x *NRequest) Reset() {
	*x = NRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notifications_notification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NRequest) ProtoMessage() {}

func (x *NRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_notification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NRequest.ProtoReflect.Descriptor instead.
func (*NRequest) Descriptor() ([]byte, []int) {
	return file_notifications_notification_proto_rawDescGZIP(), []int{2}
}

func (x *NRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NRequest) GetReferredId() uint64 {
	if x != nil {
		return x.ReferredId
	}
	return 0
}

type RequestUsername struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId           uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReferredId       uint64 `protobuf:"varint,2,opt,name=referredId,proto3" json:"referredId,omitempty"`
	ReferredUsername string `protobuf:"bytes,3,opt,name=referredUsername,proto3" json:"referredUsername,omitempty"`
}

func (x *RequestUsername) Reset() {
	*x = RequestUsername{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notifications_notification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUsername) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUsername) ProtoMessage() {}

func (x *RequestUsername) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_notification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUsername.ProtoReflect.Descriptor instead.
func (*RequestUsername) Descriptor() ([]byte, []int) {
	return file_notifications_notification_proto_rawDescGZIP(), []int{3}
}

func (x *RequestUsername) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RequestUsername) GetReferredId() uint64 {
	if x != nil {
		return x.ReferredId
	}
	return 0
}

func (x *RequestUsername) GetReferredUsername() string {
	if x != nil {
		return x.ReferredUsername
	}
	return ""
}

type NRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NRespond) Reset() {
	*x = NRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notifications_notification_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NRespond) ProtoMessage() {}

func (x *NRespond) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_notification_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NRespond.ProtoReflect.Descriptor instead.
func (*NRespond) Descriptor() ([]byte, []int) {
	return file_notifications_notification_proto_rawDescGZIP(), []int{4}
}

type NotificationCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *NotificationCount) Reset() {
	*x = NotificationCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notifications_notification_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotificationCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationCount) ProtoMessage() {}

func (x *NotificationCount) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_notification_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationCount.ProtoReflect.Descriptor instead.
func (*NotificationCount) Descriptor() ([]byte, []int) {
	return file_notifications_notification_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_notifications_notification_proto protoreflect.FileDescriptor

var file_notifications_notification_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x26, 0x0a, 0x08, 0x4e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xc4, 0x01, 0x0a, 0x0c, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x1d, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1d, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x72, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x65, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x65, 0x65,
	0x6e, 0x22, 0x42, 0x0a, 0x08, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65,
	0x64, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x72, 0x65, 0x64, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x49, 0x64,
	0x12, 0x2a, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x72, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x0a, 0x0a, 0x08,
	0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x22, 0x29, 0x0a, 0x11, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x32, 0x83, 0x03, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2e, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x6b, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x09, 0x2e, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x4e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x31, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x09, 0x2e, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e,
	0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x37, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x09, 0x2e, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x64, 0x12, 0x3e, 0x0a, 0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x09, 0x2e, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x64, 0x12, 0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x09, 0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x1a, 0x0d, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x30,
	0x01, 0x12, 0x28, 0x0a, 0x10, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x65, 0x6e, 0x12, 0x09, 0x2e, 0x4e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x1a, 0x09, 0x2e, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x3c, 0x0a, 0x1b, 0x47,
	0x65, 0x74, 0x55, 0x6e, 0x73, 0x65, 0x65, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x09, 0x2e, 0x4e, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x1a, 0x12, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x21, 0x5a, 0x1f, 0x2e, 0x2f, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notifications_notification_proto_rawDescOnce sync.Once
	file_notifications_notification_proto_rawDescData = file_notifications_notification_proto_rawDesc
)

func file_notifications_notification_proto_rawDescGZIP() []byte {
	file_notifications_notification_proto_rawDescOnce.Do(func() {
		file_notifications_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_notifications_notification_proto_rawDescData)
	})
	return file_notifications_notification_proto_rawDescData
}

var file_notifications_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_notifications_notification_proto_goTypes = []interface{}{
	(*NProfile)(nil),          // 0: NProfile
	(*Notification)(nil),      // 1: Notification
	(*NRequest)(nil),          // 2: NRequest
	(*RequestUsername)(nil),   // 3: RequestUsername
	(*NRespond)(nil),          // 4: NRespond
	(*NotificationCount)(nil), // 5: NotificationCount
}
var file_notifications_notification_proto_depIdxs = []int32{
	2, // 0: Notifications.CreateLikeNotification:input_type -> NRequest
	2, // 1: Notifications.CreateCommentNotification:input_type -> NRequest
	3, // 2: Notifications.CreateFollowNotification:input_type -> RequestUsername
	3, // 3: Notifications.CreateFollowRequestNotification:input_type -> RequestUsername
	0, // 4: Notifications.GetNotifications:input_type -> NProfile
	0, // 5: Notifications.NotificationSeen:input_type -> NProfile
	0, // 6: Notifications.GetUnseenNotificationsCount:input_type -> NProfile
	4, // 7: Notifications.CreateLikeNotification:output_type -> NRespond
	4, // 8: Notifications.CreateCommentNotification:output_type -> NRespond
	4, // 9: Notifications.CreateFollowNotification:output_type -> NRespond
	4, // 10: Notifications.CreateFollowRequestNotification:output_type -> NRespond
	1, // 11: Notifications.GetNotifications:output_type -> Notification
	4, // 12: Notifications.NotificationSeen:output_type -> NRespond
	5, // 13: Notifications.GetUnseenNotificationsCount:output_type -> NotificationCount
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notifications_notification_proto_init() }
func file_notifications_notification_proto_init() {
	if File_notifications_notification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notifications_notification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notifications_notification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notifications_notification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notifications_notification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestUsername); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notifications_notification_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notifications_notification_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotificationCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notifications_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_notification_proto_goTypes,
		DependencyIndexes: file_notifications_notification_proto_depIdxs,
		MessageInfos:      file_notifications_notification_proto_msgTypes,
	}.Build()
	File_notifications_notification_proto = out.File
	file_notifications_notification_proto_rawDesc = nil
	file_notifications_notification_proto_goTypes = nil
	file_notifications_notification_proto_depIdxs = nil
}
