// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: pki/pki.proto

package prpki

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PKIRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonName    string   `protobuf:"bytes,1,opt,name=commonName,proto3" json:"commonName,omitempty"`
	Organization  []string `protobuf:"bytes,2,rep,name=organization,proto3" json:"organization,omitempty"`
	Country       []string `protobuf:"bytes,3,rep,name=country,proto3" json:"country,omitempty"`
	Province      []string `protobuf:"bytes,4,rep,name=province,proto3" json:"province,omitempty"`
	Locality      []string `protobuf:"bytes,5,rep,name=locality,proto3" json:"locality,omitempty"`
	StreetAddress []string `protobuf:"bytes,6,rep,name=streetAddress,proto3" json:"streetAddress,omitempty"`
	PostalCode    []string `protobuf:"bytes,7,rep,name=postalCode,proto3" json:"postalCode,omitempty"`
}

func (x *PKIRegisterRequest) Reset() {
	*x = PKIRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pki_pki_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PKIRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PKIRegisterRequest) ProtoMessage() {}

func (x *PKIRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pki_pki_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PKIRegisterRequest.ProtoReflect.Descriptor instead.
func (*PKIRegisterRequest) Descriptor() ([]byte, []int) {
	return file_pki_pki_proto_rawDescGZIP(), []int{0}
}

func (x *PKIRegisterRequest) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *PKIRegisterRequest) GetOrganization() []string {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *PKIRegisterRequest) GetCountry() []string {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *PKIRegisterRequest) GetProvince() []string {
	if x != nil {
		return x.Province
	}
	return nil
}

func (x *PKIRegisterRequest) GetLocality() []string {
	if x != nil {
		return x.Locality
	}
	return nil
}

func (x *PKIRegisterRequest) GetStreetAddress() []string {
	if x != nil {
		return x.StreetAddress
	}
	return nil
}

func (x *PKIRegisterRequest) GetPostalCode() []string {
	if x != nil {
		return x.PostalCode
	}
	return nil
}

type PKIRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PKIRegisterResponse) Reset() {
	*x = PKIRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pki_pki_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PKIRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PKIRegisterResponse) ProtoMessage() {}

func (x *PKIRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pki_pki_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PKIRegisterResponse.ProtoReflect.Descriptor instead.
func (*PKIRegisterResponse) Descriptor() ([]byte, []int) {
	return file_pki_pki_proto_rawDescGZIP(), []int{1}
}

var File_pki_pki_proto protoreflect.FileDescriptor

var file_pki_pki_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x6b, 0x69, 0x2f, 0x70, 0x6b, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xf0, 0x01, 0x0a, 0x12, 0x50, 0x4b, 0x49, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x24, 0x0a, 0x0d,
	0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x4b, 0x49, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x43, 0x0a, 0x03, 0x50, 0x4b, 0x49,
	0x12, 0x3c, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x50, 0x4b, 0x49, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x50, 0x4b, 0x49, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d,
	0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x6b, 0x69, 0x2f, 0x70, 0x72, 0x70, 0x6b, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pki_pki_proto_rawDescOnce sync.Once
	file_pki_pki_proto_rawDescData = file_pki_pki_proto_rawDesc
)

func file_pki_pki_proto_rawDescGZIP() []byte {
	file_pki_pki_proto_rawDescOnce.Do(func() {
		file_pki_pki_proto_rawDescData = protoimpl.X.CompressGZIP(file_pki_pki_proto_rawDescData)
	})
	return file_pki_pki_proto_rawDescData
}

var file_pki_pki_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pki_pki_proto_goTypes = []interface{}{
	(*PKIRegisterRequest)(nil),  // 0: PKIRegisterRequest
	(*PKIRegisterResponse)(nil), // 1: PKIRegisterResponse
}
var file_pki_pki_proto_depIdxs = []int32{
	0, // 0: PKI.RegisterService:input_type -> PKIRegisterRequest
	1, // 1: PKI.RegisterService:output_type -> PKIRegisterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pki_pki_proto_init() }
func file_pki_pki_proto_init() {
	if File_pki_pki_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pki_pki_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PKIRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pki_pki_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PKIRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pki_pki_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pki_pki_proto_goTypes,
		DependencyIndexes: file_pki_pki_proto_depIdxs,
		MessageInfos:      file_pki_pki_proto_msgTypes,
	}.Build()
	File_pki_pki_proto = out.File
	file_pki_pki_proto_rawDesc = nil
	file_pki_pki_proto_goTypes = nil
	file_pki_pki_proto_depIdxs = nil
}
